services:
  web:
    image: nginx:latest
    ports:
      - 7010:80
    volumes:
      - ./back:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./back:/var/www/html
